### ISSUE TITLE
Build not available on Docker Hub

### ISSUE THREAD

**Issue by Technifocal** [linuxserver/docker-snapraid#3]
In the README you have:-

`docker create -d [...] linuxserver/snapraid`

this command fails with:-

```
Unable to find image 'linuxserver/snapraid:latest' locally
Pulling repository docker.io/linuxserver/snapraid
Error: image linuxserver/snapraid:latest not found
```

From what I can tell, this is because [the build is not available on the Docker Hub](https://hub.docker.com/search/?isAutomated=0&isOfficial=0&page=1&pullCount=0&q=snapraid&starCount=0).

While users can build this software themselves, it would be convenient to have a build available on the docker hub.

**Comment by CHBMB** [comment]
It's because we haven't released it yet.  Nor do I know if we will.

**Comment by ammmze** [comment]
@CHBMB Sorry...I know this is closed, but is there a reason you may not release this? I'm interested in running snapraid in a docker container, but may not pursue it if there's a good reason not to. Were there performance or stability issues with running this in docker?

**Comment by CHBMB** [comment]
To be honest I don't know @IronicBadger would be the person to talk to as the author...

**Comment by ironicbadger** [comment]
This never made it prime time. You can try using this build instead...

https://hub.docker.com/r/ironicbadger/docker-snapraid-debian/
